### ISSUE TITLE
Guarantee that dict keep order ?

### ISSUE THREAD

**Issue by Conchylicultor** [deepmind/tree#10]
With Python 3.6+, dict are guarantee to keep insertion order.

Currently, `tree` and `tf.nest` both seems to keep dict order, but `jax.tree_util` does not. It's not clear if this is an implementation detail or if this behavior is guaranteed.
I'm worried that the internal discussions from https://github.com/deepmind/tree/pulls#1 may lead to a regression if Jax implementation is reused.

```py
import tree
import tf
import jax

def fn(x):
  return x

data = {'z': None, 'a': None}

print(tf.nest.map_structure(fn, data))  # {'z': None, 'a': None}
print(tree.map_structure(fn, data))     # {'z': None, 'a': None}
print(jax.tree_map(fn, data))           # {'a': None, 'z': None}  << Oups, keys order inverted
```

It would be great if this behavior was documented and there was a unittest to avoid regression.

**Comment by tomhennigan** [comment]
Hey @Conchylicultor I think JAX tree functions will always return keys in sorted order because that is the order that they are iterated inside the map function:

```python
>>> d = {'e': 'e', 'a': 'a', 'b': 'b'}
>>> _ = jax.tree_map(print, d)
a
b
e
```

Tree and tf.nest actually have the same behavior (traverse dictionaries in sorted order):

```python
>>> _ = tree.map_structure(print, d)
a
b
e
```

So perhaps it is a bit odd that the return value has the insertion order of the first tree passed to map_structure (if you imagine us inserting results into the output in traversal order you would expect insertion order on the result to be sorted). Another perhaps odd quirk is that if both input dicts have different orders we use the order from the first:

```python
>>> d1 = {'e': 'e1', 'a': 'a1', 'b': 'b1'}
>>> d2 = {'a': 'a2', 'b': 'b2', 'e': 'e2'}
>>> str(tree.map_structure(lambda *_ : None, d1, d2))
{'e': None, 'a': None, 'b': None}
>>> str(tree.map_structure(lambda *_ : None, d2, d1))
{'a': None, 'b': None, 'e': None}
```

That said, this library is sufficiently popular that making a change to iteration order of the result would be a fairly major change (e.g. we would need to make sure this did not break our users) and there is no work currently planned to make this happen.

I'm not sure if the tree team want to commit to keeping insertion order for the first argument to map for ever, but I don't think this is likely to change any time soon.

**Comment by Conchylicultor** [comment]
If we were replacing `dict` by `OrderedDict`, then your above points wouldn't hold anymore. On the contrary, it would be an argument in favour of keeping insertion order.

It would feel quite inconsistent that `dict` and `OrderedDict` behave differently in Python 3.6 when `dict` are guarantee to keep insertion order.

OrderedDict sort the keys:

```
>>> tree.map_structure(print, collections.OrderedDict({'e': 'e', 'a': 'a', 'b': 'b'}))
a
b
e
```

But keep insertion order, even when there are additional arguments:

```py
>>> d1 = collections.OrderedDict({'e': 'e1', 'a': 'a1', 'b': 'b1'})
>>> d2 = collections.OrderedDict({'a': 'a2', 'b': 'b2', 'e': 'e2'})
>>> print(dict(tree.map_structure(lambda *_ : None, d1, d2)))
{'e': None, 'a': None, 'b': None}
```

The insertion key sorting is required to make sure that flattening a `dict` and `OrderedDict` match independently of the key order.

I really believe Jax behavior is a bug and the behavior should be guarantee in Tree.
