### ISSUE TITLE
Can you rename this, There is a name conflict with a main idle package

### ISSUE THREAD

**Issue by sabooakhter** [deepmind/tree#19]
If I import tree, I get a reference to this file.

C:\Users\Cybit\AppData\Local\Programs\Python\Python38\Lib\idlelib\tree.py

It's messing up my connection to tensorflow-probability, and I suspect many people have it with the error 

from tree import _assert_shallow_structure
ImportError: cannot import name '_assert_shallow_structure' from 'tree'

**Comment by impredicative** [comment]
Names should be googlable. The name `tree` fails in so many ways. Moreover, the name of the imported package currently doesn't match the name of the installed package either. I suggest the name `dmctree` for everything, including the repo, the imported Python package, and the PyPI package name.

**Comment by superbobry** [comment]
@sabooakhter I suspect the problem you're seeing is caused by a misconfigured `PYTHONPATH`. Specifically, it is likely that `[...]\Python38\Lib\idlelib` precedes the directory containing pip-installed packages in `sys.path`, effectively shadowing `tree`. So, you should be able to get rid of the error by adjusting the `PYTHONPATH`. I'm not familiar with IDLE enough, unfortunatelly, to be more specific than that.

@impredicative Thanks for sharing your thoughts. The reason the PyPI package uses `dm-tree` and not just `tree` is because the latter was taken at the time (and still [is](https://pypi.org/project/Tree/)).
